### ISSUE TITLE
Issue with TeensyStep and stm32

### ISSUE THREAD

**Issue by vpaolo** [luni64/TeensyStep#101]
Can someone help me ?

![img](https://user-images.githubusercontent.com/57304580/117833229-71cbd180-b276-11eb-8284-a5ae2bebda30.jpg)

**Comment by luni64** [comment]
I assume you are using the STM32 branch of the library? If so,  maybe @ramboerik can help. I think he also maintains has a more current STM32 fork on his gitHub  https://github.com/ramboerik.
