### ISSUE TITLE
The teensyStep controller.moveAsync() gets stuck

### ISSUE THREAD

**Issue by prajesh-asink** [luni64/TeensyStep#121]
The teensyStep controller.moveAsync() gets stuck after two to three movements. I have also tried to use while(controller.isRunning); But it is still getting stuck. I tried adding controller.stopAsync() after while(controller.isRunning); but ended up with same result. Please help.

**Comment by luni64** [comment]
Please post a minimal example showing the effect.

**Comment by prajesh-asink** [comment]
while (controller.isRunning())
      ;
      controller.stopAsync();
      
      m1.setTargetAbs(data[0]);
      m2.setTargetAbs(data[1]);
      m3.setTargetAbs(data[2]);
      m4.setTargetAbs(data[3]);
      m5.setTargetAbs(data[4]);
      m6.setTargetAbs(data[5]);
      controller.moveAsync(m1, m2, m3, m4, m5, m6);


My code keeps sending values to populate the data[] array over serial communication for a pi to teensy 3.5. But after 2 to 3 such runs it just get stuck.

**Comment by luni64** [comment]
Thanks for the snippet. Unfortunately it doesn't show much.  If you want me to help you I really need a complete sketch which I can compile and test. The sketch needs to demonstrate the issue without need for additional hardware / software.

**Comment by prajesh-asink** [comment]
Thank you so much for the prompt replies. It seems I just had to add a little delay in the while loop,

```
while (controller.isRunning())
{
     delay(1);
}
```

it is working now.
Thank you very much for your amazing work!

**Comment by luni64** [comment]
Great. 
BTW: instead of you while loop you could simply do a controller.stop().  This has the same effect as you programmed manually

**Comment by prajesh-asink** [comment]
Thanks anyway 🥂
