### ISSUE TITLE
no member named 'overrideSpeed'

### ISSUE THREAD

**Issue by EeeLo** [luni64/TeensyStep#130]
'overrideSpeed' is using now? I saw in the example but not work in my code.

**Comment by luni64** [comment]
overrideSpeed is only implemented for the rotation controllers if this is your question?

**Comment by EeeLo** [comment]
Can you give me some sample code with this?

**Comment by EeeLo** [comment]
I using StepControl controller() function to control two step motors

**Comment by EeeLo** [comment]
OK, I see, the overrideSpeed only working for rotational mode (RotateControl)

**Comment by luni64** [comment]
Here an example how to use it: https://github.com/luni64/TeensyStep/discussions/124
