### ISSUE TITLE
fatal error: algorithm: No such file or directory

### ISSUE THREAD

**Issue by lebadu** [luni64/TeensyStep#132]
We are having problems adding the TeensySteper library to the Arduino IDE. The error is described in the image below. When I try to add the algorithm library as shown below it keeps giving the error adding other libraries which are not available for use. can you help us to fix it
Thank you very much. 

![Capture](https://user-images.githubusercontent.com/104406865/165209529-3f132ad5-7732-4ae5-aec9-d5b906e607f7.PNG)

**Comment by luni64** [comment]
The lib only works for Teensy 3x. You compiled for Mega

**Comment by lebadu** [comment]
Did you mean that Lib only works when using the Teensy USB Development Board electronic circuit, it can't work directly on the Arduino Mega2560 board right?

**Comment by luni64** [comment]
Yes, only for Teensy 3.x as written in the library description: 

![image](https://user-images.githubusercontent.com/12611497/165380306-e638a6b7-03a9-45b9-9a4d-0cc055963420.png)
