### ISSUE TITLE
feature - call back function on completion of async move 

### ISSUE THREAD

**Issue by samitray** [luni64/TeensyStep#18]
In some cases it is helpful to have a feature to register a call back function  with stepcontrol class. This will eliminate the need to poll isRunning() method and possibly simplify program flow.

Cheers
Samit

**Comment by luni64** [comment]
Thanks for the input. Great idea, shouldn't be too difficult to implement. I'll add this as soon as I have some time. 
Lutz

**Comment by mgcrea** [comment]
@luni64 Awesome work with the lib, would love a callback method too! 👍
