### ISSUE TITLE
typo in readme

### ISSUE THREAD

**Issue by GradeSchool** [luni64/TeensyStep#21]
motor_1.setPostion(pos);             // set a new value of the step counter 

setPosition

threw me off a bit :)

**Comment by GradeSchool** [comment]
Also in readme

.setInvertedDir(true)

should be 

.setInverseRotation(true);

**Comment by GradeSchool** [comment]
PS this library is awesome :)

**Comment by conkerts** [comment]
Ah, that's good, there is already a thread for the readme.
So as it's too much hassle to fork this project for typos, I write it here.

I tried the example code at Used Resources and got:
'class StepControl<>' has no member named 'isOK'

This is probably, b/c the method is named isOk() in the source.

Cheers

**Comment by luni64** [comment]
All fixed, thank you
