### ISSUE TITLE
Synchronous Movement with more than 3 motors

### ISSUE THREAD

**Issue by conkerts** [luni64/TeensyStep#24]
Hi, this looks like a really great library with a neat interface.

I'm trying to move 4 motors at the same time. As the readme states "the controller accepts up to 10 motors in its move and moveAsync command. All motors which are passed to the commands will be moved synchronously."

So when I try to compile my code, I get the following error:

```
controller.move(M1,M2,M3,M4);    // Do the move
                            ^
no matching function for call to 'StepControl<>::move(Stepper&, Stepper&, Stepper&, Stepper&)'

```
Same with
 ```
controller.moveAsync(M1,M2,M3,M4);    // Do the move
                                 ^
no matching function for call to 'StepControl<>::moveAsync(Stepper&, Stepper&, Stepper&, Stepper&)'

```

With 3 Motor objects the code runs flawlessly.

So before I modify anything in StepControl.h in the template definitions, I decided to ask here ;)
I checked out the latest git version.

Cheers

**Comment by luni64** [comment]
Was just about to write you that there is an example :-)
