### ISSUE TITLE
Does this library work for Arduino?

### ISSUE THREAD

**Issue by poplawa** [luni64/TeensyStep#37]
Hi. This might be a silly question but I've never used Teensy before.  I tried to use this library for my Arduino Mega but got plenty of built errors (missing libraries). Is there a way o use this library on ARDUINO?

**Comment by luni64** [comment]
Sorry, this library only works with Teensies. But Teensies are fully compatible to the Arduino oekosystem. You can program and use them like a Mega just install [Teensyduino](https://www.pjrc.com/teensy/teensyduino.html) to your Arduino IDE
