### ISSUE TITLE
Setting Steps with Button Input

### ISSUE THREAD

**Issue by bradmcco1** [luni64/TeensyStep#41]
Hi,
I am using a Teensy 3.6 to control 2x Nema 34 Stepper motors through two drivers. I have the STEP and DIR pins connected to the Teensy along with a UP and Down Button.

I would like the motors to move up while holding the UP button and the motors to move down while holding the down button. 
I am having issues writing the correct code for this, as it results in the motor going very slow & the motor is jumping/skipping.

Thanks

**Comment by luni64** [comment]
See [here](https://forum.pjrc.com/threads/55380-Setting-steps-with-external-button?p=200215&viewfull=1#post200215)
