### ISSUE TITLE
moveAsync for an array of steppers

### ISSUE THREAD

**Issue by eshkrab** [luni64/TeensyStep#5]
Hello! The readme says that a controller can control up to ten motors but I'm confused about the usage of the function. I thought, if motors is an array of stepper pointers, the way to call the function would be controller.moveAsync(motors); but that causes the Teensy to crash. What's the correct way to do this? 
Thanks!

**Comment by luni64** [comment]
@eshkrab
Can you post your code? I can have a look at it tomorrow

**Comment by luni64** [comment]
I added an [example](https://github.com/luni64/TeensyStep/tree/master/examples/StepperArray) which shows how to use arrays of pointers to steppers, hope that helps.

**Comment by eshkrab** [comment]
thank you! I'm not obviously doing something different so perhaps it's crashing for another reason, but the example helps!
