### ISSUE TITLE
Speed not 0 after emergency stop

### ISSUE THREAD

**Issue by badVibes--** [luni64/TeensyStep#55]
Hey, I think the getCurrentSpeed() should return 0 after an emergency stop. I think right now it returns the last speed before the stop was called.

**Comment by luni64** [comment]
Yes that's a known bug (see https://github.com/luni64/TeensyStep/issues/49#issuecomment-499847557) and will be fixed in the next release. 

Meanwhile you can workaround by 
```c++
int32_t speed = controller.isRunning() ? controller.getCurrentFrequency() : 0; 
```
