### ISSUE TITLE
setPullInSpeed() not recognised in library

### ISSUE THREAD

**Issue by thierryhubert333** [luni64/TeensyStep#60]
I'm trying to use the function motor.setPullInspeed(800); as on the site example. but it doesn't recognize it when i compile. I'm using a teensy 3.5. I tried looking in the library and can't find it anywhere.

**Comment by luni64** [comment]
Sorry, this is not part of the currently released version.  However, you can use the devTimer branch which includes it. I'll release this branch together with the Teensy 4 adaptions later this year.

**Comment by thierryhubert333** [comment]
Later this year, do you still mean 2019? I don't mean to put pressure or anyhting, just to be clear. Thank you for your fast response.

**Comment by luni64** [comment]
Does anything speak against using the DevTimer branch?  The more people testing it the better :-)

**Comment by thierryhubert333** [comment]
Oops, im sorry. I'm not experienced with github. I didn't know i could just be part of that and download it. Thank you, I will test it!
