### ISSUE TITLE
Motion doesn't stop with some combination of speed/acceleration

### ISSUE THREAD

**Issue by imwhocodes** [luni64/TeensyStep#61]
Hi
First of all thank you for this high performance library, loving it from release 1

I'm having trouble with some motion settings, it happens that with some combinations of speed and acceleration motion doesn't stop and the motor keep running indefinitely

The behavior is that the motor keep slowing down normally while approaching the target position until the speed reach a plateau and it keep going at that speed overshooting the target and never stopping

This behavior happen mostly setting high acceleration and slow motion speed, both using moveAsync and/or stopAsync

I'm using TeensyStep V2 with the default interpolation and pulselength values  on a Teensy3.6

Any idea why?

Thank

**Comment by luni64** [comment]
Can you post a (ideally small) sketch showing the effect?
