### ISSUE TITLE
Missed steps 

### ISSUE THREAD

**Issue by 1DropDiag** [luni64/TeensyStep#71]
First of all, thanks for the amazing library.

I am running TeensyStep v2.0 on a teensy 3.5 with a HSB57 controller and 57HBS22. These are hybrind controllers and motors that correct for missesd steps thanks to the integrated encoder.

Here are the details of my set-up:
- Teensy 3.5 @240MHz
- StepControl(10,10000)
- Speed: 65000 steps/s
- Acc: 180000 steps/s^2
- Counts per rotation: 12500

All works fine most of the time but the motor stall for no apparent reason when I enter a shift of cetain number of steps (for ex.: 95, 187, 243, 311,...). Addin or removing 1 step to these numbers removes the stalling. I've not been able to see a pattern. Longer travels (> 12500 turns) do not trigger the issue. 
If I change the accelleration value, the numbers of stepds triggering the issu changes slightly. Speed changes seem to have no effect.  This happens on two different stages.

Would you have any idea where the issue could come from? Is it possible that these step values could give a bad accelleration profile or that they stall the board for a small amount of time?

**Comment by luni64** [comment]
Sounds very strange, can you post a minimal example showing this effect? I can then have a look at the generated pulse sequences
