### ISSUE TITLE
Great project! and Thanks

### ISSUE THREAD

**Issue by vangalvin** [luni64/TeensyStep#72]
This is not an issue just really a thank you for your hard work. 

I have just set this up on a hight torque Novotech SC60SCD40D motor and SC6780 controller. These are hybrid servo drives with an encoder built in and a few extra features. 

The Teensy 3.2 seems to have no issues with it. I am hoping to break out the encder pins and the alarm pin so i can track the distances the motor has moved and test to see if there is an error.

**Comment by luni64** [comment]
Great, let me know if you find any issues
