### ISSUE TITLE
H-bridge motor control

### ISSUE THREAD

**Issue by firelizzard18** [luni64/TeensyStep#90]
Can I use this with an H-bridge motor driver? I have an Adafruit [TB6612 breakout](https://www.adafruit.com/product/2448). It is not a dedicated stepper controller. It has two motor channels, A and B, both of which have input 1, input 2, and a pwm input. I can use the regular Arduino stepper library by initializing with `Stepper stepper(StepsPerRev, AIN2, AIN1, BIN1, BIN2)`.

**Comment by luni64** [comment]
Sorry, but this won't work. TeensyStep is outputting STP/DIR signals not the signals needed for low level driving a stepper. While driving steppers with a H-bridge driver somehow works and was kind of common in the last century, these days real stepper drivers are readily available and very cheap. I strongly suggest to get one of the usual DRV8825 or A4988 or similar. 

Here some info about stepper drivers https://luni64.github.io/TeensyStep/applications2/902_drivers/drivers and here info about steppers:  https://luni64.github.io/TeensyStep/applications2/901_stepper/steppers
